### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by lupus721** [k8gege/K8PortScan#1]
应该增加个报告输出功能，或者默认生成一个扫描报告，扫的内容多的时候，直接就被刷过去了。。

**Comment by k8gege** [comment]
暂不打算添加，重定向输出文本即可

**Comment by k8gege** [comment]
> 
> 
> 应该增加个报告输出功能，或者默认生成一个扫描报告，扫的内容多的时候，直接就被刷过去了。。

暂不打算添加，重定向输出文本即可
